import medicineModel from "../models/pharmacyModel.js";

const defaultMedicines = [
  {"name":"Paracetamol 500mg","manufacturer":"Sun Pharma","category":"Tablet","dosage":"500mg","price":50,"stock":120,"requiresPrescription":false,"description":"Used to treat fever and mild pain."},
  {"name":"Amoxicillin 250mg","manufacturer":"Cipla","category":"Capsule","dosage":"250mg","price":120,"stock":80,"requiresPrescription":true,"description":"Antibiotic used for bacterial infections."},
  {"name":"Ibuprofen 400mg","manufacturer":"Dr Reddy's","category":"Tablet","dosage":"400mg","price":70,"stock":150,"requiresPrescription":false,"description":"Pain reliever and anti-inflammatory."},
  {"name":"Azithromycin 500mg","manufacturer":"Cipla","category":"Tablet","dosage":"500mg","price":180,"stock":90,"requiresPrescription":true,"description":"Used for bacterial infections."},
  {"name":"Cough Syrup DX","manufacturer":"Zydus","category":"Syrup","dosage":"100ml","price":90,"stock":60,"requiresPrescription":false,"description":"Relief from dry cough."},
  {"name":"Vitamin D3 Drops","manufacturer":"Himalaya","category":"Drops","dosage":"30ml","price":150,"stock":70,"requiresPrescription":false,"description":"Supports bone health."},
  {"name":"Insulin Injection","manufacturer":"Novo Nordisk","category":"Injection","dosage":"10ml","price":600,"stock":40,"requiresPrescription":true,"description":"Used to control blood sugar levels."},
  {"name":"Skin Ointment","manufacturer":"Glenmark","category":"Ointment","dosage":"20g","price":110,"stock":100,"requiresPrescription":false,"description":"Used for skin infections."},
  {"name":"Asthma Inhaler","manufacturer":"Cipla","category":"Inhaler","dosage":"200 doses","price":350,"stock":55,"requiresPrescription":true,"description":"Helps in breathing for asthma patients."},
  {"name":"Multivitamin Supplement","manufacturer":"HealthKart","category":"Supplement","dosage":"60 tablets","price":500,"stock":75,"requiresPrescription":false,"description":"Boosts immunity and energy."},
  {"name":"Metformin 500mg","manufacturer":"Sun Pharma","category":"Tablet","dosage":"500mg","price":60,"stock":140,"requiresPrescription":true,"description":"Used for diabetes control."},
  {"name":"Pantoprazole 40mg","manufacturer":"Dr Reddy's","category":"Tablet","dosage":"40mg","price":85,"stock":110,"requiresPrescription":false,"description":"Reduces stomach acid."},
  {"name":"ORS Sachet","manufacturer":"Dabur","category":"Other","dosage":"1 sachet","price":20,"stock":200,"requiresPrescription":false,"description":"Prevents dehydration."},
  {"name":"Cetirizine 10mg","manufacturer":"Zydus","category":"Tablet","dosage":"10mg","price":40,"stock":160,"requiresPrescription":false,"description":"Used for allergies."},
  {"name":"Montelukast 10mg","manufacturer":"Cipla","category":"Tablet","dosage":"10mg","price":130,"stock":95,"requiresPrescription":true,"description":"Used for asthma and allergies."},
  {"name":"Calcium Tablets","manufacturer":"Himalaya","category":"Supplement","dosage":"500mg","price":200,"stock":85,"requiresPrescription":false,"description":"Supports bone strength."},
  {"name":"Diclofenac Gel","manufacturer":"Glenmark","category":"Ointment","dosage":"30g","price":140,"stock":90,"requiresPrescription":false,"description":"Relieves muscle pain."},
  {"name":"Amoxiclav 625mg","manufacturer":"Sun Pharma","category":"Tablet","dosage":"625mg","price":220,"stock":70,"requiresPrescription":true,"description":"Broad spectrum antibiotic."},
  {"name":"Loperamide","manufacturer":"Zydus","category":"Capsule","dosage":"2mg","price":60,"stock":130,"requiresPrescription":false,"description":"Used for diarrhea."},
  {"name":"Ranitidine 150mg","manufacturer":"Cipla","category":"Tablet","dosage":"150mg","price":55,"stock":120,"requiresPrescription":false,"description":"Reduces stomach acid."},
  {"name":"Folic Acid","manufacturer":"Sun Pharma","category":"Tablet","dosage":"5mg","price":45,"stock":140,"requiresPrescription":false,"description":"Used for anemia."},
  {"name":"Iron Syrup","manufacturer":"Dabur","category":"Syrup","dosage":"200ml","price":120,"stock":80,"requiresPrescription":false,"description":"Treats iron deficiency."},
  {"name":"Dexamethasone","manufacturer":"Cipla","category":"Injection","dosage":"2ml","price":90,"stock":60,"requiresPrescription":true,"description":"Steroid medication."},
  {"name":"Saline IV","manufacturer":"Baxter","category":"Injection","dosage":"500ml","price":150,"stock":100,"requiresPrescription":true,"description":"Used for hydration."},
  {"name":"Paracetamol Syrup","manufacturer":"Zydus","category":"Syrup","dosage":"60ml","price":65,"stock":110,"requiresPrescription":false,"description":"Fever relief for kids."},
  {"name":"Rabeprazole","manufacturer":"Dr Reddy's","category":"Tablet","dosage":"20mg","price":95,"stock":105,"requiresPrescription":false,"description":"Treats acidity."},
  {"name":"Aspirin","manufacturer":"Cipla","category":"Tablet","dosage":"75mg","price":30,"stock":200,"requiresPrescription":false,"description":"Blood thinner."},
  {"name":"Clopidogrel","manufacturer":"Sun Pharma","category":"Tablet","dosage":"75mg","price":140,"stock":75,"requiresPrescription":true,"description":"Prevents heart attack."},
  {"name":"Atorvastatin","manufacturer":"Dr Reddy's","category":"Tablet","dosage":"10mg","price":160,"stock":90,"requiresPrescription":true,"description":"Controls cholesterol."},
  {"name":"Losartan","manufacturer":"Cipla","category":"Tablet","dosage":"50mg","price":120,"stock":100,"requiresPrescription":true,"description":"Treats high BP."},
  {"name":"Telmisartan","manufacturer":"Sun Pharma","category":"Tablet","dosage":"40mg","price":130,"stock":95,"requiresPrescription":true,"description":"Blood pressure control."},
  {"name":"Levocetirizine","manufacturer":"Zydus","category":"Tablet","dosage":"5mg","price":50,"stock":150,"requiresPrescription":false,"description":"Allergy relief."},
  {"name":"Mefenamic Acid","manufacturer":"Cipla","category":"Tablet","dosage":"250mg","price":75,"stock":110,"requiresPrescription":false,"description":"Pain relief."},
  {"name":"Tramadol","manufacturer":"Sun Pharma","category":"Capsule","dosage":"50mg","price":180,"stock":60,"requiresPrescription":true,"description":"Moderate pain relief."},
  {"name":"Ondansetron","manufacturer":"Dr Reddy's","category":"Tablet","dosage":"4mg","price":90,"stock":85,"requiresPrescription":true,"description":"Prevents nausea."},
  {"name":"Domperidone","manufacturer":"Cipla","category":"Tablet","dosage":"10mg","price":70,"stock":100,"requiresPrescription":false,"description":"Treats vomiting."},
  {"name":"Hydrocortisone Cream","manufacturer":"Glenmark","category":"Ointment","dosage":"15g","price":120,"stock":80,"requiresPrescription":false,"description":"Skin inflammation relief."},
  {"name":"Betadine Solution","manufacturer":"Himalaya","category":"Other","dosage":"100ml","price":90,"stock":120,"requiresPrescription":false,"description":"Antiseptic solution."},
  {"name":"Insulin Rapid","manufacturer":"Novo Nordisk","category":"Injection","dosage":"10ml","price":750,"stock":30,"requiresPrescription":true,"description":"Rapid insulin for diabetes."},
  {"name":"Zinc Supplement","manufacturer":"HealthKart","category":"Supplement","dosage":"50mg","price":220,"stock":70,"requiresPrescription":false,"description":"Boosts immunity."},
  {"name":"Vitamin C Tablets","manufacturer":"Dabur","category":"Supplement","dosage":"500mg","price":150,"stock":90,"requiresPrescription":false,"description":"Immune support."},
  {"name":"Antacid Syrup","manufacturer":"Zydus","category":"Syrup","dosage":"200ml","price":110,"stock":85,"requiresPrescription":false,"description":"Relieves acidity."},
  {"name":"Erythromycin","manufacturer":"Cipla","category":"Tablet","dosage":"250mg","price":140,"stock":75,"requiresPrescription":true,"description":"Antibiotic."},
  {"name":"Chlorpheniramine","manufacturer":"Sun Pharma","category":"Tablet","dosage":"4mg","price":40,"stock":130,"requiresPrescription":false,"description":"Allergy relief."},
  {"name":"Heparin Injection","manufacturer":"Baxter","category":"Injection","dosage":"5ml","price":500,"stock":40,"requiresPrescription":true,"description":"Blood thinner injection."},
  {"name":"Glucon-D","manufacturer":"Dabur","category":"Other","dosage":"500g","price":180,"stock":60,"requiresPrescription":false,"description":"Energy drink powder."},
  {"name":"Diclofenac Injection","manufacturer":"Sun Pharma","category":"Injection","dosage":"3ml","price":95,"stock":80,"requiresPrescription":true,"description":"Pain relief injection."},
  {"name":"B Complex Capsules","manufacturer":"Zydus","category":"Capsule","dosage":"1 capsule","price":90,"stock":100,"requiresPrescription":false,"description":"Vitamin supplement."},
  {"name":"Ketoconazole Cream","manufacturer":"Glenmark","category":"Ointment","dosage":"20g","price":150,"stock":70,"requiresPrescription":false,"description":"Antifungal cream."},
  {"name":"Fluconazole","manufacturer":"Cipla","category":"Tablet","dosage":"150mg","price":160,"stock":65,"requiresPrescription":true,"description":"Antifungal medication."},
  {"name":"Salbutamol Syrup","manufacturer":"Cipla","category":"Syrup","dosage":"100ml","price":95,"stock":90,"requiresPrescription":false,"description":"Asthma relief syrup."},
  {"name":"Lactulose Syrup","manufacturer":"Sun Pharma","category":"Syrup","dosage":"200ml","price":180,"stock":75,"requiresPrescription":false,"description":"Treats constipation."},
  {"name":"Nitroglycerin","manufacturer":"Dr Reddy's","category":"Tablet","dosage":"2.5mg","price":200,"stock":50,"requiresPrescription":true,"description":"Heart medication."},
  {"name":"Warfarin","manufacturer":"Cipla","category":"Tablet","dosage":"5mg","price":220,"stock":45,"requiresPrescription":true,"description":"Blood thinner."},
  {"name":"Spironolactone","manufacturer":"Sun Pharma","category":"Tablet","dosage":"25mg","price":110,"stock":85,"requiresPrescription":true,"description":"Diuretic."},
  {"name":"Furosemide","manufacturer":"Zydus","category":"Tablet","dosage":"40mg","price":60,"stock":120,"requiresPrescription":true,"description":"Water pill."},
  {"name":"Glimepiride","manufacturer":"Sun Pharma","category":"Tablet","dosage":"2mg","price":95,"stock":90,"requiresPrescription":true,"description":"Diabetes medicine."},
  {"name":"Pioglitazone","manufacturer":"Cipla","category":"Tablet","dosage":"15mg","price":130,"stock":80,"requiresPrescription":true,"description":"Blood sugar control."},
  {"name":"Alprazolam","manufacturer":"Sun Pharma","category":"Tablet","dosage":"0.5mg","price":140,"stock":60,"requiresPrescription":true,"description":"Anxiety treatment."},
  {"name":"Diazepam","manufacturer":"Zydus","category":"Tablet","dosage":"5mg","price":90,"stock":70,"requiresPrescription":true,"description":"Sedative."},
  {"name":"Codeine Syrup","manufacturer":"Cipla","category":"Syrup","dosage":"100ml","price":180,"stock":50,"requiresPrescription":true,"description":"Cough suppressant."},
  {"name":"ORS Liquid","manufacturer":"Dabur","category":"Syrup","dosage":"200ml","price":60,"stock":100,"requiresPrescription":false,"description":"Hydration support."},
  {"name":"Eye Drops","manufacturer":"Sun Pharma","category":"Drops","dosage":"10ml","price":120,"stock":85,"requiresPrescription":false,"description":"For eye irritation."},
  {"name":"Ear Drops","manufacturer":"Zydus","category":"Drops","dosage":"10ml","price":110,"stock":75,"requiresPrescription":false,"description":"Ear infection relief."},
  {"name":"Nasal Spray","manufacturer":"Cipla","category":"Other","dosage":"15ml","price":150,"stock":70,"requiresPrescription":false,"description":"Nasal congestion relief."},
  {"name":"Protein Powder","manufacturer":"HealthKart","category":"Supplement","dosage":"1kg","price":1200,"stock":40,"requiresPrescription":false,"description":"Muscle building supplement."},
  {"name":"Calamine Lotion","manufacturer":"Himalaya","category":"Ointment","dosage":"100ml","price":130,"stock":80,"requiresPrescription":false,"description":"Skin soothing lotion."},
  {"name":"Glucose Tablets","manufacturer":"Dabur","category":"Tablet","dosage":"10 tablets","price":60,"stock":110,"requiresPrescription":false,"description":"Instant energy."},
  {"name":"Cefixime","manufacturer":"Cipla","category":"Tablet","dosage":"200mg","price":180,"stock":70,"requiresPrescription":true,"description":"Antibiotic."},
  {"name":"Ofloxacin","manufacturer":"Sun Pharma","category":"Tablet","dosage":"200mg","price":160,"stock":75,"requiresPrescription":true,"description":"Antibacterial."},
  {"name":"Levofloxacin","manufacturer":"Dr Reddy's","category":"Tablet","dosage":"500mg","price":200,"stock":65,"requiresPrescription":true,"description":"Antibiotic."},
  {"name":"Amikacin Injection","manufacturer":"Baxter","category":"Injection","dosage":"2ml","price":250,"stock":50,"requiresPrescription":true,"description":"Antibiotic injection."},
  {"name":"Vitamin E Capsules","manufacturer":"Zydus","category":"Capsule","dosage":"400mg","price":150,"stock":80,"requiresPrescription":false,"description":"Skin health."},
  {"name":"Magnesium Tablets","manufacturer":"HealthKart","category":"Supplement","dosage":"250mg","price":300,"stock":60,"requiresPrescription":false,"description":"Muscle function."},
  {"name":"Melatonin","manufacturer":"Sun Pharma","category":"Tablet","dosage":"3mg","price":220,"stock":55,"requiresPrescription":false,"description":"Sleep aid."},
  {"name":"Prednisolone","manufacturer":"Cipla","category":"Tablet","dosage":"10mg","price":140,"stock":75,"requiresPrescription":true,"description":"Steroid."}
];

export const seedPharmacyMedicines = async () => {
  const existing = await medicineModel.countDocuments();
  if (existing > 0) return;

  const now = Date.now();
  const docs = defaultMedicines.map((m, idx) => ({
    ...m,
    available: true,
    date: now + idx
  }));

  await medicineModel.insertMany(docs);
};
